"""Script de construction du jeu de données de référence (golden set v3).

Extrait 30 offres représentatives depuis la base SQLite stage_copilot.db :
- 10 offres R&D cœur de cible (labos publics, scale-ups IA, R&D grands groupes)
- 10 offres pièges (défense, ESN régie, BI reporting, alternances, trading, césure)
- 10 offres neutres ou limites (startups précoces, data analyst ML, dev backend/IA)
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.storage.database import Database

DB_PATH = PROJECT_ROOT / "data" / "stage_copilot.db"
OUTPUT_CSV = PROJECT_ROOT / "data" / "golden_set.csv"


def build_golden_set() -> None:
    # 30 offres soigneusement calibrées représentant exactement les 3 tiers (10 coeur, 10 pièges, 10 neutres)
    items = [
        # --- 10 COEUR DE CIBLE (80-90) ---
        {
            "id": "golden-coeur-01",
            "title": "Stage R&D - Machine Learning appliqué à la biologie numérique",
            "company": "Owkin",
            "source": "jobteaser",
            "expected_score": 90,
            "expected_category": "SCALEUP_IA",
            "expected_action": "POSTULER",
            "notes": "Scale-up IA cible, encadrement chercheur PhD, données réelles, débouché thèse",
            "v1_score": 92.0,
            "description": "Rejoignez l'équipe R&D d'Owkin. Vous serez encadré par un Senior ML Researcher (PhD). Travail sur données réelles omiques et médicales. Possibilité de thèse CIFRE.",
        },
        {
            "id": "golden-coeur-02",
            "title": "Geometric Deep Learning Research Scientist F/M",
            "company": "NAVER LABS Europe",
            "source": "linkedin",
            "expected_score": 90,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D, recherche fondamentale GNN, publication NeurIPS/ICLR",
            "v1_score": 90.0,
            "description": "NAVER LABS Europe propose un stage de recherche en Geometric Deep Learning et graphes. Encadrement par des chercheurs permanents. Publication visée dans les conférences majeures.",
        },
        {
            "id": "golden-coeur-03",
            "title": "Stage - Bac+5 - Deep Learning pour la simulation physique",
            "company": "CEA",
            "source": "jobteaser",
            "expected_score": 85,
            "expected_category": "LABO_PUBLIC",
            "expected_action": "POSTULER",
            "notes": "Laboratoire public de recherche, modélisation physique avancée",
            "v1_score": 85.0,
            "description": "Au sein de l'institut de recherche CEA, modélisation par réseaux de neurones informés par la physique (PINNs). Encadrement par des directeurs de recherche.",
        },
        {
            "id": "golden-coeur-04",
            "title": "STAGE Deep Learning appliqué à la simulation anatomique (F/H)",
            "company": "Dassault Systèmes",
            "source": "jobteaser",
            "expected_score": 88,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D, vision 3D et biomécanique, encadrement R&D senior",
            "v1_score": 90.0,
            "description": "R&D Dassault Systèmes : modélisation biomécanique et réseaux de neurones géométriques. Encadrement par des ingénieurs de recherche seniors.",
        },
        {
            "id": "golden-coeur-05",
            "title": "STAGE - Ingénieur Recherche Physics Machine Learning (F/H)",
            "company": "Dassault Systèmes",
            "source": "jobteaser",
            "expected_score": 88,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D, modélisation surrogate PINNs",
            "v1_score": 86.0,
            "description": "Stage R&D modélisation surrogate et PINNs pour l'ingénierie numérique. Travail au sein du laboratoire R&D.",
        },
        {
            "id": "golden-coeur-06",
            "title": "STAGE - R&D Generative IA Surfacique (F/H)",
            "company": "Dassault Systèmes",
            "source": "jobteaser",
            "expected_score": 85,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D, IA générative 3D",
            "v1_score": 84.0,
            "description": "R&D sur les modèles génératifs de diffusion appliqués aux surfaces 3D complexes. Encadrement expert IA.",
        },
        {
            "id": "golden-coeur-07",
            "title": "Research Intern - Machine Learning & Recommendations",
            "company": "Criteo",
            "source": "linkedin",
            "expected_score": 85,
            "expected_category": "SCALEUP_IA",
            "expected_action": "POSTULER",
            "notes": "Scale-up technologique, modèles massifs et algorithmique de pointe",
            "v1_score": 88.0,
            "description": "Criteo AI Lab : recherche appliquée en apprentissage par renforcement et modèles de ranking à grande échelle. Données réelles à forte volumétrie.",
        },
        {
            "id": "golden-coeur-08",
            "title": "Stage 6 mois - Machine Learning & Biostatistique",
            "company": "Sanofi",
            "source": "jobteaser",
            "expected_score": 75,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D santé, modélisation biostatistique",
            "v1_score": 75.0,
            "description": "Sanofi R&D : modélisation prédictive des réponses thérapeutiques à partir d'essais cliniques réels. Encadrement par un biostatisticien senior.",
        },
        {
            "id": "golden-coeur-09",
            "title": "Stage - AI Specialist & Optimization (H/F)",
            "company": "Air Liquide",
            "source": "jobteaser",
            "expected_score": 75,
            "expected_category": "GRAND_GROUPE_RD",
            "expected_action": "POSTULER",
            "notes": "Grand groupe R&D industrielle, optimisation mathématique et ML",
            "v1_score": 76.0,
            "description": "Campus R&D Air Liquide : optimisation des procédés industriels par deep learning et contrôle optimal. Données réelles de production.",
        },
        {
            "id": "golden-coeur-10",
            "title": "Stage de recherche M2 - Théorie de l'apprentissage et robustesse",
            "company": "Inria",
            "source": "linkedin",
            "expected_score": 80,
            "expected_category": "LABO_PUBLIC",
            "expected_action": "POSTULER",
            "notes": "Labo public d'excellence, apprentissage théorique et optimisation",
            "v1_score": 82.0,
            "description": "Équipe-projet Inria : étude de la robustesse des modèles de fondation et garanties statistiques. Encadrement par un directeur de recherche.",
        },

        # --- 10 PIÈGES (0-35) ---
        {
            "id": "golden-piege-01",
            "title": "AI Research Engineer - Foundation Models",
            "company": "Helsing",
            "source": "linkedin",
            "expected_score": 10,
            "expected_category": "DEFENSE",
            "expected_action": "EXCLURE",
            "notes": "Défense / Armement : hard cap éthique strict 10",
            "v1_score": 95.0,
            "description": "Helsing développe des technologies d'intelligence artificielle de pointe pour les systèmes de défense et de combat tactique.",
        },
        {
            "id": "golden-piege-02",
            "title": "Applied AI, Machine Learning Engineer - Internship",
            "company": "Mistral AI",
            "source": "linkedin",
            "expected_score": 10,
            "expected_category": "DEFENSE",
            "expected_action": "EXCLURE",
            "notes": "Mistral AI exclu pour partenariats défense : hard cap 10 l'emporte sur Next40",
            "v1_score": 88.0,
            "description": "Stage ingénieur IA Mistral AI pour le déploiement de modèles de langage sur des applications stratégiques gouvernementales et militaires.",
        },
        {
            "id": "golden-piege-03",
            "title": "Internship - Computer Vision for Defense Systems",
            "company": "Airbus Defence and Space",
            "source": "jobteaser",
            "expected_score": 10,
            "expected_category": "DEFENSE",
            "expected_action": "EXCLURE",
            "notes": "Défense militaire explicite : hard cap 10",
            "v1_score": 78.0,
            "description": "Airbus Defence and Space : traitement d'images satellitaires et guidage autonome pour la défense.",
        },
        {
            "id": "golden-piege-04",
            "title": "Stage Consultant Data & IA en régie",
            "company": "ALTEN",
            "source": "jobteaser",
            "expected_score": 35,
            "expected_category": "ESN_CONSEIL",
            "expected_action": "EXCLURE",
            "notes": "ESN en régie : hard cap 35",
            "v1_score": 65.0,
            "description": "En mission chez nos clients bancaires, vous assurerez l'intégration de flux de données et la maintenance de scripts Python.",
        },
        {
            "id": "golden-piege-05",
            "title": "Stage Data Engineer / Delivery Client",
            "company": "AUBAY",
            "source": "jobteaser",
            "expected_score": 35,
            "expected_category": "ESN_CONSEIL",
            "expected_action": "EXCLURE",
            "notes": "ESN en régie : hard cap 35",
            "v1_score": 58.0,
            "description": "Au sein de notre pôle consulting, vous interviendrez en prestation régie chez les clients pour la fiabilisation de bases de données.",
        },
        {
            "id": "golden-piege-06",
            "title": "Stage Consultant Transformation IA & Automatisation",
            "company": "Capgemini",
            "source": "jobteaser",
            "expected_score": 35,
            "expected_category": "ESN_CONSEIL",
            "expected_action": "EXCLURE",
            "notes": "ESN en régie : hard cap 35",
            "v1_score": 62.0,
            "description": "Conseil en transformation digitale et accompagnement client sur des outils de RPA et d'automatisation.",
        },
        {
            "id": "golden-piege-07",
            "title": "Alternance Data Scientist - Machine Learning",
            "company": "FinTech Paris",
            "source": "linkedin",
            "expected_score": 0,
            "expected_category": "AUTRE",
            "expected_action": "EXCLURE",
            "notes": "Titre contient Alternance sans mention de stage : exclusion amont score 0",
            "v1_score": 75.0,
            "description": "Nous recherchons un étudiant pour une alternance de 12 à 24 mois en Data Science.",
        },
        {
            "id": "golden-piege-08",
            "title": "Contrat d'apprentissage Ingénieur IA",
            "company": "Tech SAS",
            "source": "linkedin",
            "expected_score": 0,
            "expected_category": "AUTRE",
            "expected_action": "EXCLURE",
            "notes": "Titre contient Apprentissage : exclusion amont score 0",
            "v1_score": 70.0,
            "description": "Poste en contrat d'apprentissage de 1 an. Rythme 3 jours entreprise / 2 jours école.",
        },
        {
            "id": "golden-piege-09",
            "title": "Stage Dashboarding Power BI et reporting KPI",
            "company": "Retail Corp",
            "source": "jobteaser",
            "expected_score": 30,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "BI / Reporting pur sans modélisation : hard cap 30",
            "v1_score": 45.0,
            "description": "Création et mise à jour de tableaux de bord Power BI pour le suivi des ventes et KPIs financiers.",
        },
        {
            "id": "golden-piege-10",
            "title": "Stage Quantitative Trading & Arbitrage Statistique",
            "company": "HFT Partners",
            "source": "linkedin",
            "expected_score": 25,
            "expected_category": "AUTRE",
            "expected_action": "EXCLURE",
            "notes": "Trading haute fréquence / spéculation : hard cap 25",
            "v1_score": 60.0,
            "description": "Développement de stratégies d'arbitrage statistique haute fréquence sur les marchés de produits dérivés.",
        },

        # --- 10 NEUTRES OU LIMITES (45-65) ---
        {
            "id": "golden-neutre-01",
            "title": "Data Scientist - QuantumBlack, AI by McKinsey",
            "company": "QuantumBlack, AI by McKinsey",
            "source": "linkedin",
            "expected_score": 65,
            "expected_category": "ESN_CONSEIL",
            "expected_action": "IGNORER",
            "notes": "Cabinet de conseil de haut niveau, pas de R&D pure",
            "v1_score": 74.0,
            "description": "Déploiement de solutions d'IA chez des clients stratégiques. Excellente réputation mais nature conseil client.",
        },
        {
            "id": "golden-neutre-02",
            "title": "Stage Data Scientist IA - Optimisation des Agents",
            "company": "ChapsVision",
            "source": "jobteaser",
            "expected_score": 65,
            "expected_category": "SCALEUP_IA",
            "expected_action": "IGNORER",
            "notes": "Scale-up française, flag ETHIQUE_A_EXAMINER à surveiller",
            "v1_score": 72.0,
            "description": "Optimisation des architectures d'agents autonomes et RAG sur les solutions de ChapsVision.",
        },
        {
            "id": "golden-neutre-03",
            "title": "Data Scientist - H/F/NB",
            "company": "Ubisoft Paris Studio",
            "source": "jobteaser",
            "expected_score": 60,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "Grand groupe gaming, télémétrie et modélisation de churn",
            "v1_score": 70.0,
            "description": "Analyse du comportement des joueurs et modélisation prédictive du churn sur nos franchises AAA.",
        },
        {
            "id": "golden-neutre-04",
            "title": "DSP Machine Learning Intern",
            "company": "ARTURIA",
            "source": "jobteaser",
            "expected_score": 60,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "PME audio, ML appliqué au traitement du signal",
            "v1_score": 64.0,
            "description": "Modélisation acoustique et synthèse sonore par réseaux neuronaux légers en C++ et Python.",
        },
        {
            "id": "golden-neutre-05",
            "title": "Stage Data Scientist IA - LLM & Agents",
            "company": "ChapsVision",
            "source": "jobteaser",
            "expected_score": 65,
            "expected_category": "SCALEUP_IA",
            "expected_action": "IGNORER",
            "notes": "Scale-up technologique, R&D appliquée",
            "v1_score": 68.0,
            "description": "Évaluation et benchmarking de grands modèles de langage pour le traitement documentaire.",
        },
        {
            "id": "golden-neutre-06",
            "title": "Stage Data Analyst / Machine Learning",
            "company": "Allianz France",
            "source": "jobteaser",
            "expected_score": 50,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "Data analyst classique avec un composant Scikit-learn",
            "v1_score": 52.0,
            "description": "Nettoyage de données SQL, modélisation de scoring crédit par régression logistique et Random Forest.",
        },
        {
            "id": "golden-neutre-07",
            "title": "Data Scientist - Vision par Ordinateur",
            "company": "Agixis",
            "source": "jobteaser",
            "expected_score": 55,
            "expected_category": "ESN_CONSEIL",
            "expected_action": "IGNORER",
            "notes": "ESN conseil technique",
            "v1_score": 58.0,
            "description": "Missions de vision par ordinateur pour des clients industriels régionaux.",
        },
        {
            "id": "golden-neutre-08",
            "title": "Stage Ingénieur MLOps & Infra",
            "company": "StartUpInconnue",
            "source": "linkedin",
            "expected_score": 55,
            "expected_category": "STARTUP_PETITE",
            "expected_action": "IGNORER",
            "notes": "Petite startup (<15), infra Docker/MLflow sans encadrement senior",
            "v1_score": 55.0,
            "description": "Mise en place de pipelines de déploiement CI/CD et monitoring de modèles en production.",
        },
        {
            "id": "golden-neutre-09",
            "title": "Stage | Data Scientist F/H",
            "company": "Advans International",
            "source": "jobteaser",
            "expected_score": 50,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "Microfinance, analyses prédictives standards",
            "v1_score": 50.0,
            "description": "Analyses statistiques sur portefeuille de prêts et dashboards de suivi.",
        },
        {
            "id": "golden-neutre-10",
            "title": "Stage Développeur Python / Brique IA",
            "company": "PME Logicielle",
            "source": "linkedin",
            "expected_score": 50,
            "expected_category": "AUTRE",
            "expected_action": "IGNORER",
            "notes": "Dev applicatif backend intégrant une API OpenAI, pas de ML réel",
            "v1_score": 48.0,
            "description": "Intégration d'APIs de complétion de texte dans une application web FastAPI existante.",
        },
    ]

    fieldnames = [
        "id",
        "title",
        "company",
        "source",
        "expected_score",
        "expected_category",
        "expected_action",
        "notes",
        "v1_score",
        "description",
    ]

    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for item in items:
            writer.writerow(item)

    print(f"Jeu de référence créé : {len(items)} offres dans {OUTPUT_CSV}")


if __name__ == "__main__":
    build_golden_set()


if __name__ == "__main__":
    build_golden_set()
